# Generated by Django 4.0.2 on 2022-02-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe',
            field=models.CharField(default='stripe', max_length=200),
            preserve_default=False,
        ),
    ]
