# Generated by Django 4.0.2 on 2022-02-02 13:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.UUIDField(default=uuid.UUID('155cc061-b35c-4fd1-93ab-fe07d350510f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6916cc50-109b-47da-bdc5-67da5a0d18c4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
