# Generated by Django 4.0.2 on 2022-02-02 15:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.UUIDField(default=uuid.UUID('492e3142-ca2a-4ee6-b3db-556d25760e45'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1a3b5dec-3c90-42c2-a850-ee15a0e07cc0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
