# Generated by Django 4.0.2 on 2022-02-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_stripe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe',
        ),
    ]
