# Generated by Django 4.0.2 on 2022-02-02 13:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_order_no_alter_orderitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.UUIDField(default=uuid.UUID('56225d99-694c-4a83-adcb-59553801020d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c6edcd01-8f40-47e5-8454-49c64f1c8991'), editable=False, primary_key=True, serialize=False),
        ),
    ]
