# Generated by Django 4.0.2 on 2022-02-02 13:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_order_no_alter_orderitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.UUIDField(default=uuid.UUID('75dd7491-85f0-40dc-8e84-86d50bede7b2'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9fa91413-0566-43a8-a010-52b6739e9810'), editable=False, primary_key=True, serialize=False),
        ),
    ]
