# Generated by Django 4.0.2 on 2022-02-04 13:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.TextField()),
                ('price', models.PositiveSmallIntegerField()),
                ('cost', models.PositiveIntegerField()),
                ('quantity', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
