# Generated by Django 4.0.2 on 2022-02-01 13:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('product_id', models.UUIDField(default=uuid.UUID('65047d6e-ed52-4442-8979-7fb333dd6959'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=150)),
                ('price', models.PositiveSmallIntegerField()),
                ('cost', models.PositiveIntegerField()),
                ('quantity', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
