# Generated by Django 4.0.2 on 2022-02-02 13:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('2ae2e368-2e5d-43fa-8bc6-02a1d8116512'), editable=False, primary_key=True, serialize=False),
        ),
    ]
