# Generated by Django 4.0.2 on 2022-02-02 15:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('647236c6-ab04-4dbe-8b74-5755055cf5b3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
