# Generated by Django 4.0.2 on 2022-02-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='author',
            field=models.CharField(default='author', max_length=150),
            preserve_default=False,
        ),
    ]
