# Generated by Django 4.0.2 on 2022-02-01 14:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('0d95ef27-0dc7-4ea8-a22d-8733635b1207'), editable=False, primary_key=True, serialize=False),
        ),
    ]
