# Generated by Django 4.0.2 on 2022-02-02 13:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('5fa9b902-68e4-4b10-aafe-6e8455cba9e6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
