# Generated by Django 4.0.2 on 2022-02-02 13:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('76258efa-e7e5-401f-809f-38f4a2a4c941'), editable=False, primary_key=True, serialize=False),
        ),
    ]
