# Generated by Django 4.0.2 on 2022-02-03 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_account_cart_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
